#!/usr/bin/env ansible-playbook
---
- name: Delete all Instances
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
     - cloud.info
     - gce/authentication
     - gce/defaults
  tasks:
    - set_fact: region={{ gce_default_region }}
      when: region is not defined

    - set_fact: zone={{ gce_default_zone }}
      when: zone is not defined

    - name: Deleting each instance
      gce:
        instance_names: "{{ item.name }}"
        zone: "{{ zone }}"
        state: "absent"
        project_id: "{{ gce_project_id }}"
        credentials_file: "{{ gce_credentials_file }}"
        service_account_email: "{{ gce_service_account_email }}"
      with_items: "{{ openshift }}"
      register: 

    - name: Deleting all Docker Storages
      gce_pd:
        name: "{{ item.name }}-docker"
        zone: "{{ zone }}"
        state: absent
        project_id: "{{ gce_project_id }}"
        credentials_file: "{{ gce_credentials_file }}"
        service_account_email: "{{ gce_service_account_email }}"
      with_items: "{{ openshift }}"
