---
- name: Create a Network on Google Compute Engine
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
     - cloud.info
     - gce/authentication
     - gce/defaults
  tasks:
    - include: commons/setting_defaults.yaml

    - name: Create the network
      gce_net: 
        name: "{{ network_name }}"
        mode: custom
        subnet_name: "{{ subnetwork_name }}"
        subnet_region: "{{ region }}"
        ipv4_range: "{{ subnetwork_range }}"
        state: present
        project_id: "{{ gce_project_id }}"
        credentials_file: "{{ gce_credentials_file }}"
        service_account_email: "{{ gce_service_account_email }}"  
      tags: 
         - create_network

    - name: Create all the necessary firewall rules for network{{ ':' }} {{ network_name }}
      gce_net:
        name: "{{ network_name }}"
        fwname: "{{ item.name }}"
        allowed: "{{ item.allow }}"
        src_range: "[{{ item.range }}]"
        target_tags: "{{ item.tag }}"
        state: present
        project_id: "{{ gce_project_id }}"
        credentials_file: "{{ gce_credentials_file }}"
        service_account_email: "{{ gce_service_account_email }}"  
      with_items: "{{ openshift_firewall_rules }}"
      tags: 
         - create_network       


