---
- name: Test
  hosts: localhost
  connection: local
  vars:
     machine_type: n1-standard-1
     region: us-east1
     service_account_email: maltron@quick-cacao-157517.iam.gserviceaccount.com
     credentials_file: /home/mauricio/.gce/maltron.json
     project_id: quick-cacao-157517
  tasks:
    - name: Create a Network named maltron
      gce_net: name="maltron"
               mode="custom" subnet_name="maltron-subnet" subnet_region="{{ region }}" ipv4_range="192.168.0.0/16"
               project_id="{{ project_id }}" credentials_file="{{ credentials_file }}" service_account_email="{{ service_account_email }}"

    - name: Allow HTTP traffic
      gce_net: name="maltron" 
               fwname="all-http-maltron" allowed="tcp:80" state="present"
               project_id="{{ project_id }}" credentials_file="{{ credentials_file }}" service_account_email="{{ service_account_email }}"
      tags:
         - http

#     - name: Create a Network
#       gce_net: name="hello" state=present
#                mode=custom  subnet_name=hello-subnet  subnet_region={{ zone }} ipv4_range="192.168.0.0/16"
#                service_account_email="{{ service_account_email }}" credentials_file="{{ credentials_file }}" project_id="{{ project_id }}"

#     - name: Create Firewall Rule
#       gce_net: name="hello" fwname="enable-ssh" allowed="tcp:22" state=present
#                service_account_email={{ service_account_email }} credentials_file={{ credentials_file }} project_id={{ project_id }}

#     - name: Create instance
#       gce: instance_names="Hello" machine_type={{ machine_type }} image="rhel73" zone={{ zone }} state=present
#            service_account_email={{ service_account_email }} credentials_file={{ credentials_file }} project_id={{ project_id }}  
#       register: networking
#
#     - debug: var=networking
